      double precision autoang
      integer maxatom,maxpair,maxdata,maxterm,maxperm
      parameter(autoang=0.529177249d0)
      parameter(maxatom=10)    ! max total atoms
      parameter(maxpair=5)    ! max atom-atoms pairs
      parameter(maxdata=20000) ! max fitting data
      parameter(maxterm=500000) ! max number of polynomial terms
      parameter(maxperm=10000000)    ! max number of symmetry permutations

